### Operadores ###

print(3 + 4)
print(3 - 4)
print(3 * 4)
print(3 / 4)
print(10 % 3)
print(10 // 3)
print(2 ** 3)

print('Hola ' + 'Python')

print('Hola '*int(2.5*2))

## Operadores Comparativos

"""print(3 > 4)
print(3 < 4)
print(3 >= 4)
print(3 <= 4)
print(4 == 4)
print(3 != 4)"""


print('Hola' > 'Python')
print('Hola' < 'Python')
print('Hola' >= 'Python')
print('Hola' <= 'Python')
print('Hola' == 'Bola')
print('Hola' != 'Python')


## Operadores logicos##

print(4 == 4 and 'Hola' > 'Python')
print(2 > 4 or 'Hola' > 'Python')
print(2 < 4 or 'Hola' > 'Hola')
print(not(2 > 4 ))